version: "3"

services:  
  api-ura-abasteceai-develop:
    image: $REGISTRY
    logging:
      driver: "json-file"
      options:
         max-file: 1
         max-size: 10m   
    hostname: apiuraabasteceaidevelop
    ports:
     - "7551:80" 
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    deploy:
      placement:
        constraints:
        - node.role == manager